[package]
name = "azarole"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]
edition = "2024"

[[bin]]
name = "azarole"
path = "src/main.rs"

[dependencies]
actix-cors = "0.7.1"
actix-rt = "2.11.0"
actix-service = "2.0.3"
actix-session = { version = "0.11.0", features = ["cookie-session"] }
actix-web = "4.11.0"
anyhow = "~1.0.99"
clap = { version = "~4.5.47", features = ["derive"] }
serde = "~1.0.226"
serde_derive = "~1.0.226"
sqlx = { version = "~0.8.6", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.47.1", features = ["fs", "macros", "rt-multi-thread"] }
toml = "~0.9.7"
